import {
  Activity,
  AlertTriangle,
  Award,
  BadgeCheck,
  Boxes,
  CalendarCheck,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  FlaskConical,
  Gauge,
  GraduationCap,
  HardHat,
  HeartPulse,
  IndianRupee,
  PauseCircle,
  PlayCircle,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  UserX,
  Wrench,
  XCircle,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  wrench: Wrench,
  clock: Clock,
  calendar: CalendarCheck,
  clipboard: ClipboardList,
  rupee: IndianRupee,
  gauge: Gauge,
  users: Users,
  userCheck: UserCheck,
  userX: UserX,
  trendingUp: TrendingUp,
  star: Star,
  smile: Smile,
  sparkles: Sparkles,
  award: Award,
  badgeCheck: BadgeCheck,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  flask: FlaskConical,
  target: Target,
  clipboardCheck: ClipboardCheck,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  alertTriangle: AlertTriangle,
  hardHat: HardHat,
  graduationCap: GraduationCap,
  boxes: Boxes,
  cpu: Cpu,
  playCircle: PlayCircle,
  pauseCircle: PauseCircle,
  settings: Settings,
  heartPulse: HeartPulse,
  activity: Activity,
};
