import {
  Activity,
  AlertTriangle,
  Award,
  BadgeCheck,
  Boxes,
  CalendarCheck,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  Cpu,
  Droplets,
  Flame,
  FlaskConical,
  Gauge,
  GraduationCap,
  HardHat,
  HeartPulse,
  IndianRupee,
  Layers,
  Leaf,
  ListChecks,
  Package,
  PauseCircle,
  Percent,
  PlayCircle,
  Recycle,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Target,
  Thermometer,
  Trash2,
  TrendingUp,
  Truck,
  UserCheck,
  Users,
  UserX,
  Wallet,
  Wind,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  wrench: Wrench,
  clock: Clock,
  calendar: CalendarCheck,
  clipboard: ClipboardList,
  rupee: IndianRupee,
  gauge: Gauge,
  users: Users,
  userCheck: UserCheck,
  userX: UserX,
  trendingUp: TrendingUp,
  star: Star,
  smile: Smile,
  sparkles: Sparkles,
  award: Award,
  badgeCheck: BadgeCheck,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  flask: FlaskConical,
  target: Target,
  clipboardCheck: ClipboardCheck,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  alertTriangle: AlertTriangle,
  hardHat: HardHat,
  graduationCap: GraduationCap,
  boxes: Boxes,
  cpu: Cpu,
  playCircle: PlayCircle,
  pauseCircle: PauseCircle,
  settings: Settings,
  heartPulse: HeartPulse,
  activity: Activity,
  wallet: Wallet,
  percent: Percent,
  truck: Truck,
  zap: Zap,
  package: Package,
  listChecks: ListChecks,
  layers: Layers,
  droplets: Droplets,
  recycle: Recycle,
  wind: Wind,
  thermometer: Thermometer,
  stethoscope: Stethoscope,
  cloud: Cloud,
  leaf: Leaf,
  trash: Trash2,
  sun: Sun,
  flame: Flame,
};
